hosts: 
        -
               host: localhost
               port: 9000 
        -
                host: localhost
                port: 9001 
        -
                host: localhost
                port: 9002 
        -
                host: localhost
                port: 9003 
        -
                host: localhost
                port: 9004
